# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 320370b232270b378a56b8b5f7bc72cb1d77dcdd31f6b64662545d443ea410a49f370163c049b97a9e10248f1fd4bc81fe0bb817c9dd538d90cbf3f5a57fc22f

test:
  secret_key_base: 222dc031adeec5b63eb11460d7e9f23f0d2518f772dc9e5fe3f859c0f550fa02779e538647b5bd94884ff94b4d7b7f4f7d4f413f01e99bc3e3c4d19cd95a38ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
